#!/bin/sh

PXESERVER=10.0.0.1

# This script will run the first time the system boots. Even
# though we've told it to run after networking is enabled,
#
# Introducing a brief sleep makes things work right all the
# time. The time for DHCP to catch up.
sleep 60

# install our new sources
cat > /etc/apt/sources.list <<EOF
deb http://$PXESERVER:3142/debian wheezy main contrib non-free
deb http://debian.saltstack.com/debian wheezy-saltstack main

EOF

echo "APT::Get::AllowUnauthenticated yes;" > /etc/apt/apt.conf.d/99auth

# add salt key
wget -q -O- "http://debian.saltstack.com/debian-salt-team-joehealy.gpg.key" | apt-key add -

# update apt
/usr/bin/apt-get update

# Install the salt client
apt-get install --yes --no-install-recommends --force-yes salt-minion

sed -i -e "s|#master: salt|master: $PXESERVER|" /etc/salt/minion

/etc/init.d/salt-minion restart

# download configuration files
/usr/bin/curl -o /tmp/iplist http://$PXESERVER/iplist

# get ip and detect hostname
_ip=`ip addr list eth0 |grep 'inet ' |cut -d' ' -f6|cut -d/ -f1`
hostname=`grep $_ip /tmp/iplist | awk '{print $1}'`
rm /tmp/iplist

# set hostname
echo $hostname > /etc/hostname
/etc/init.d/hostname.sh

# Remove our firstboot service so that it won't run again
update-rc.d firstboot remove
rm /etc/init.d/firstboot /root/firstboot

# Reboot into the new kernel
/sbin/reboot
